name = "cm-room"
main = "src/worker.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]

[env.dev]
name = "cm-room-dev"

[env.dev.vars]
MATCHMAKER_URL = "https://cm-matchmaker-dev.seanreid.workers.dev"

[[env.dev.durable_objects.bindings]]
name = "ROOM"
class_name = "Room"

[env.production]
name = "cm-room"

[env.production.vars]
MATCHMAKER_URL = "https://cm-matchmaker.seanreid.workers.dev"

[[env.production.durable_objects.bindings]]
name = "ROOM"
class_name = "Room"
